FROM python:3.9.13

WORKDIR /user/src/app

COPY requirements.txt ./       # ./  ==> points to /user/src/app



RUN pip install  --no -cache-dir -r requirements.txt 

COPY ..    # ( copy all of our source code  /user/src/app in the current directory)

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--post", "8000"]

